import Foundations.MarketActions.Primitive

/-!
# Market Actions: Analytic Properties

Blueprint module for
`1 - theoretical foundations/3_market_actions.tex`,
subsection "Analytical Results for Primitive Actions".

Planned formal content:

* `thm:analytic-properties-actions`;
* continuity of concatenation, cancellation, and modification;
* `cor:sorted-operations-measurable`.
-/

namespace Thesis
namespace Foundations
namespace MarketActions
namespace Analytic

open Thesis.Foundations.MarketRepresentation
open Thesis.Foundations.MarketRepresentation.FiniteSets
open Thesis.Foundations.MarketRepresentation.FiniteSets.FiniteSubsets
open Thesis.Foundations.MarketRepresentation.TuplesBasic
open Thesis.Foundations.MarketRepresentation.TuplesMetricTopology
open Thesis.Foundations.MarketRepresentation.TuplesSorting
open Thesis.Foundations.MarketActions.Primitive

universe u

/-! ## Explicit Metric Borel Structures -/

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: topological/measurable convention behind
`cor:sorted-operations-measurable`.

Informal statement: use the topology induced by the extended metric.

Lean strategy / thesis relation note: several thesis spaces are represented in Lean as subtypes or
Sigma types, which have native topologies in mathlib. This reducible wrapper
names the thesis metric topology so measurability statements below use the
same topology as the epsilon-delta continuity proofs.
-/
@[reducible]
noncomputable def emetricTopology (α : Type u) [PseudoEMetricSpace α] :
    TopologicalSpace α :=
  PseudoEMetricSpace.toUniformSpace.toTopologicalSpace

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: measurable convention behind
`cor:sorted-operations-measurable`.

Informal statement: the Borel sigma-algebra generated by the thesis extended
metric topology.
-/
@[reducible]
noncomputable def emetricBorel (α : Type u) [PseudoEMetricSpace α] :
    MeasurableSpace α :=
  @borel α (emetricTopology α)

/-! ## Index Stabilization for Cancellation -/

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: index-stabilization step inside
`thm:analytic-properties-actions`, cancellation part.

Informal statement: natural-number indices are isolated at scale `1`.

Lean strategy / thesis relation note: this reuses the earlier formalization of
`lem:helpful-distinct`: in the usual metric on `ℕ`, edistance `< 1` forces
equality.

Lean strategy / thesis strategy note: this is only the natural-number isolation ingredient used
inside the analytic-actions proof. The theorem-level formalization of
`lem:helpful-distinct` is in `FiniteSets.lean`, especially
`DistinctFiniteSubsets.exists_same_index_near_of_edist_lt_one` and
`DistinctFiniteSubsets.ncard_eq_of_edist_lt_one`.
-/
theorem nat_isolative_bound_one : Isolative ℕ := by
  refine ⟨1, zero_lt_one, ?_⟩
  intro n m hne
  by_contra hnot
  exact hne (IndexAugmented.nat_eq_of_edist_lt_one (lt_of_not_ge hnot))

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: index-stabilization step inside
`thm:analytic-properties-actions`, cancellation part.

Informal statement: finite subsets of natural-number indices are locally
constant at Hausdorff radius `1`.

Lean strategy / thesis relation note: the thesis phrases this as an isolative-space argument. Lean
spells it out using the previously proved theorem that finite Hausdorff spaces
inherit isolativity from their ambient space.

Lean strategy / thesis strategy note: this is the finite-subset-of-`ℕ` specialization needed for
the cancellation part of `thm:analytic-properties-actions`, not a replacement
for the full distinct finite-set lemma.
-/
theorem finiteSubsets_nat_eq_of_edist_lt_one
    {eta eta₀ : FiniteSubsets ℕ}
    (h : edist eta eta₀ < (1 : ENNReal)) :
    eta = eta₀ := by
  by_contra hne
  have hNatSep : ∀ n m : ℕ, n ≠ m → (1 : ENNReal) ≤ edist n m := by
    intro n m hne_nm
    by_contra hnot
    exact hne_nm (IndexAugmented.nat_eq_of_edist_lt_one (lt_of_not_ge hnot))
  have hset_ne : (eta : Set ℕ) ≠ (eta₀ : Set ℕ) := by
    intro hset
    exact hne (Subtype.ext hset)
  have hle : (1 : ENNReal) ≤ edist eta eta₀ := by
    change (1 : ENNReal) ≤ hausdorffEDistance eta eta₀
    by_cases hsubset : (eta : Set ℕ) ⊆ (eta₀ : Set ℕ)
    · have hnot : ¬ (eta₀ : Set ℕ) ⊆ (eta : Set ℕ) := by
        intro hsubset'
        exact hset_ne (Set.Subset.antisymm hsubset hsubset')
      rcases Set.not_subset.mp hnot with ⟨n, hneta₀, hneta⟩
      rw [hausdorffEDistance_comm]
      exact hausdorffEDistance_lower_bound_of_mem_notMem hNatSep hneta₀ hneta
    · rcases Set.not_subset.mp hsubset with ⟨n, hneta, hneta₀⟩
      exact hausdorffEDistance_lower_bound_of_mem_notMem hNatSep hneta hneta₀
  exact (not_lt_of_ge hle) h

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: length-stabilization step inside
`thm:analytic-properties-actions`, cancellation part.

Informal statement: if two tuples have the same length, then their finite
natural-number domains coincide.

Lean strategy / thesis relation note: the thesis uses `{1, ..., \ell(x)}`; Lean uses the zero-based
domain `{n | n < x.length}`.
-/
theorem tupleDomain_eq_of_length_eq {X : Type u} {x y : Tuple X}
    (h : x.length = y.length) :
    tupleDomain x = tupleDomain y := by
  apply Subtype.ext
  ext n
  simp [tupleDomain, h]

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: surviving-index step inside
`thm:analytic-properties-actions`, cancellation part.

Informal statement: below radius `1`, both the tuple domain and cancellation
set stabilize, so the surviving index set used by cancellation is identical.

Lean strategy / thesis relation note: this is the formal version of the thesis step saying that the
same finite subset of coordinates is removed, after shrinking the
epsilon-delta neighborhood below the isolation radius.
-/
theorem cancel_survivorSet_eq_of_near {X : Type u} [EMetricSpace X]
    {x x₀ : Tuple X} {eta eta₀ : FiniteSubsets ℕ}
    (hx : edist x x₀ < (1 : ENNReal))
    (heta : edist eta eta₀ < (1 : ENNReal)) :
    finiteSubsetDiff (tupleDomain x) eta =
      finiteSubsetDiff (tupleDomain x₀) eta₀ := by
  have hDomain : tupleDomain x = tupleDomain x₀ :=
    tupleDomain_eq_of_length_eq (length_eq_of_edist_lt_one hx)
  have hEta : eta = eta₀ := finiteSubsets_nat_eq_of_edist_lt_one heta
  simp [hDomain, hEta]

/-! ## Concatenation -/

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: quantitative estimate inside
`thm:analytic-properties-actions`, concatenation part.

Informal statement: after the thesis' length-stabilization step, appending
two fixed-length pairs of tuples cannot increase the coordinate maximum beyond
the larger of the two input coordinate maxima.

Lean strategy / thesis relation note: the thesis writes tuples as indexed finite sequences. Lean
represents the fixed-length layers as functions `Fin n -> X`, and
concatenation is `Fin.append` on those functions.
-/
theorem coordinateEDistSup_append_le_max {X : Type u} [EMetricSpace X]
    {m n : ℕ} (x x₀ : Fin m → X) (y y₀ : Fin n → X) :
    coordinateEDistSup (Fin.append x y) (Fin.append x₀ y₀) ≤
      max (coordinateEDistSup x x₀) (coordinateEDistSup y y₀) := by
  apply Finset.sup_le
  intro i _hi
  refine Fin.addCases ?left ?right i
  · intro j
    have hleft :
        edist (x j) (x₀ j) ≤ coordinateEDistSup x x₀ := by
      simpa [coordinateEDistSup] using
        (Finset.le_sup (s := Finset.univ)
          (f := fun k : Fin m => edist (x k) (x₀ k)) (Finset.mem_univ j))
    simpa using le_trans hleft (le_max_left _ _)
  · intro j
    have hright :
        edist (y j) (y₀ j) ≤ coordinateEDistSup y y₀ := by
      simpa [coordinateEDistSup] using
        (Finset.le_sup (s := Finset.univ)
          (f := fun k : Fin n => edist (y k) (y₀ k)) (Finset.mem_univ j))
    simpa using le_trans hright (le_max_right _ _)

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: quantitative estimate inside
`thm:analytic-properties-actions`, concatenation part.

Informal statement: on fixed-length tuple layers, the tuple Hausdorff distance
between concatenations is bounded by the larger coordinate maximum of the two
input pairs.

Lean strategy / thesis relation note: this is the formal version of the proof line where the thesis
reduces the output Hausdorff distance to a maximum over the concatenated list
of coordinates.
-/
theorem concat_edist_le_max_coordinate {X : Type u} [EMetricSpace X]
    {m n : ℕ} (x x₀ : Fin m → X) (y y₀ : Fin n → X) :
    edist (concat (Sigma.mk m x : Tuple X) (Sigma.mk n y : Tuple X))
        (concat (Sigma.mk m x₀ : Tuple X) (Sigma.mk n y₀ : Tuple X)) ≤
      max (coordinateEDistSup x x₀) (coordinateEDistSup y y₀) := by
  calc
    edist (concat (Sigma.mk m x : Tuple X) (Sigma.mk n y : Tuple X))
        (concat (Sigma.mk m x₀ : Tuple X) (Sigma.mk n y₀ : Tuple X))
        ≤ coordinateEDistSup (Fin.append x y) (Fin.append x₀ y₀) := by
          simpa [concat, Tuple.length, Tuple.entry] using
            (fixedLength_edist_le_coordinateEDistSup
              (X := X) (x := Fin.append x y) (y := Fin.append x₀ y₀))
    _ ≤ max (coordinateEDistSup x x₀) (coordinateEDistSup y y₀) :=
        coordinateEDistSup_append_le_max x x₀ y y₀

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: local fixed-length estimate inside
`thm:analytic-properties-actions`, concatenation part.

Informal statement: once the inputs are within the local radius `1`, where the
tuple Hausdorff distance is exactly the coordinate maximum, concatenation is
nonexpansive with respect to the product maximum distance.

Lean strategy / thesis relation note: this is still the fixed-layer form. The full theorem in the
thesis first uses `length_eq_of_edist_lt_one` to move arbitrary nearby tuples
into such fixed layers.
-/
theorem concat_edist_le_max_of_fixed_lt_one {X : Type u} [EMetricSpace X]
    {m n : ℕ} {x x₀ : Fin m → X} {y y₀ : Fin n → X}
    (hx : edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) <
      (1 : ENNReal))
    (hy : edist (Sigma.mk n y : Tuple X) (Sigma.mk n y₀ : Tuple X) <
      (1 : ENNReal)) :
    edist (concat (Sigma.mk m x : Tuple X) (Sigma.mk n y : Tuple X))
        (concat (Sigma.mk m x₀ : Tuple X) (Sigma.mk n y₀ : Tuple X)) ≤
      max (edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X))
        (edist (Sigma.mk n y : Tuple X) (Sigma.mk n y₀ : Tuple X)) := by
  calc
    edist (concat (Sigma.mk m x : Tuple X) (Sigma.mk n y : Tuple X))
        (concat (Sigma.mk m x₀ : Tuple X) (Sigma.mk n y₀ : Tuple X))
        ≤ max (coordinateEDistSup x x₀) (coordinateEDistSup y y₀) :=
          concat_edist_le_max_coordinate x x₀ y y₀
    _ = max (edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X))
        (edist (Sigma.mk n y : Tuple X) (Sigma.mk n y₀ : Tuple X)) := by
          rw [← fixedLength_edist_eq_coordinateEDistSup_of_lt_one hx,
            ← fixedLength_edist_eq_coordinateEDistSup_of_lt_one hy]

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: epsilon-delta estimate inside
`thm:analytic-properties-actions`, concatenation part.

Informal statement: in a fixed-length layer, if both input tuple distances are
below a common bound `δ < 1`, then the concatenated tuple distance is also
below `δ`.

Lean strategy / thesis relation note: the thesis states this inside the continuity proof with
`δ < min(1, ε)`. Lean records the reusable metric implication directly.
-/
theorem concat_edist_lt_of_fixed_lt {X : Type u} [EMetricSpace X]
    {m n : ℕ} {x x₀ : Fin m → X} {y y₀ : Fin n → X} {δ : ENNReal}
    (hx_one : edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) <
      (1 : ENNReal))
    (hy_one : edist (Sigma.mk n y : Tuple X) (Sigma.mk n y₀ : Tuple X) <
      (1 : ENNReal))
    (hxδ : edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) < δ)
    (hyδ : edist (Sigma.mk n y : Tuple X) (Sigma.mk n y₀ : Tuple X) < δ) :
    edist (concat (Sigma.mk m x : Tuple X) (Sigma.mk n y : Tuple X))
        (concat (Sigma.mk m x₀ : Tuple X) (Sigma.mk n y₀ : Tuple X)) < δ := by
  exact lt_of_le_of_lt (concat_edist_le_max_of_fixed_lt_one hx_one hy_one)
    ((max_lt_iff).mpr ⟨hxδ, hyδ⟩)

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: `thm:analytic-properties-actions`, concatenation part.

Informal statement: tuple concatenation is continuous for the tuple Hausdorff
extended metric.

Lean strategy / thesis relation note: this is the type-theoretic version of the thesis proof. Given
nearby arbitrary tuples, `length_eq_of_edist_lt_one` first transports them
into the same fixed-length layers as the base point; the fixed-layer estimate
above then proves the epsilon-delta bound.
-/
theorem continuousAt_concat_emetricTopology {X : Type u} [EMetricSpace X]
    (p₀ : Tuple X × Tuple X) :
    @ContinuousAt (Tuple X × Tuple X) (Tuple X)
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      (fun p : Tuple X × Tuple X => concat p.1 p.2) p₀ := by
  letI : TopologicalSpace (Tuple X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  letI : TopologicalSpace (Tuple X × Tuple X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  rcases p₀ with ⟨x₀Tuple, y₀Tuple⟩
  rcases x₀Tuple with ⟨m, x₀⟩
  rcases y₀Tuple with ⟨n, y₀⟩
  rw [ContinuousAt, EMetric.tendsto_nhds_nhds]
  intro ε hε
  let δ : ENNReal := min ε (1 : ENNReal)
  refine ⟨δ, lt_min hε zero_lt_one, ?_⟩
  intro p hp
  rcases p with ⟨xTuple, yTuple⟩
  rcases xTuple with ⟨m', x⟩
  rcases yTuple with ⟨n', y⟩
  rw [Prod.edist_eq] at hp
  have hxδ :
      edist (Sigma.mk m' x : Tuple X) (Sigma.mk m x₀ : Tuple X) < δ :=
    (max_lt_iff.mp hp).1
  have hyδ :
      edist (Sigma.mk n' y : Tuple X) (Sigma.mk n y₀ : Tuple X) < δ :=
    (max_lt_iff.mp hp).2
  have hx_one :
      edist (Sigma.mk m' x : Tuple X) (Sigma.mk m x₀ : Tuple X) <
        (1 : ENNReal) :=
    lt_of_lt_of_le hxδ (min_le_right _ _)
  have hy_one :
      edist (Sigma.mk n' y : Tuple X) (Sigma.mk n y₀ : Tuple X) <
        (1 : ENNReal) :=
    lt_of_lt_of_le hyδ (min_le_right _ _)
  have hm : m' = m := by
    simpa [Tuple.length] using length_eq_of_edist_lt_one hx_one
  have hn : n' = n := by
    simpa [Tuple.length] using length_eq_of_edist_lt_one hy_one
  subst m'
  subst n'
  have houtδ :
      edist (concat (Sigma.mk m x : Tuple X) (Sigma.mk n y : Tuple X))
          (concat (Sigma.mk m x₀ : Tuple X) (Sigma.mk n y₀ : Tuple X)) < δ :=
    concat_edist_lt_of_fixed_lt hx_one hy_one hxδ hyδ
  exact lt_of_lt_of_le houtδ (min_le_left _ _)

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: `thm:analytic-properties-actions`, concatenation part.

Informal statement: tuple concatenation is continuous for the explicit
topology induced by the tuple Hausdorff extended metric.

Lean strategy / thesis relation note: `Tuple X` is definitionally a Sigma type, so Lean also has a
native Sigma topology available. The thesis result is metric-topological; a
later tuple-topology bridge should identify this explicit metric topology
with the default Sigma topology when needed downstream.
-/
theorem continuous_concat_emetricTopology {X : Type u} [EMetricSpace X] :
    @Continuous (Tuple X × Tuple X) (Tuple X)
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      (fun p : Tuple X × Tuple X => concat p.1 p.2) := by
  letI : TopologicalSpace (Tuple X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  letI : TopologicalSpace (Tuple X × Tuple X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  rw [continuous_iff_continuousAt]
  exact continuousAt_concat_emetricTopology

/-! ## Cancellation -/

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: quantitative estimate inside
`thm:analytic-properties-actions`, cancellation part.

Informal statement: after the thesis' stabilization step has fixed the same
finite set of indices to keep, reindexing a fixed-length tuple is
nonexpansive with respect to the coordinate maximum distance.

Lean strategy / thesis relation note: Lean's `reindex` compresses surviving natural-number indices
through the `pairing` enumeration. The proof follows the thesis proof: every
output coordinate is one of the original input coordinates.
-/
theorem reindex_edist_le_coordinate {X : Type u} [EMetricSpace X]
    {m : ℕ} (x x₀ : Fin m → X) (eta : FiniteSubsets ℕ) :
    edist (reindex (Sigma.mk m x : Tuple X) eta)
        (reindex (Sigma.mk m x₀ : Tuple X) eta) ≤
      coordinateEDistSup x x₀ := by
  let kept : FiniteSubsets ℕ :=
    finiteSubsetInter eta (tupleDomain (Sigma.mk m x : Tuple X))
  let p : Tuple ℕ := pairing kept
  have hcoord :
      coordinateEDistSup
          (fun i : Fin p.length =>
            x ⟨Tuple.entry p i, by
              have hmem : Tuple.entry p i ∈ (kept : Set ℕ) :=
                pairing_entry_mem kept i
              exact (mem_tupleDomain (Sigma.mk m x : Tuple X)).mp hmem.2⟩)
          (fun i : Fin p.length =>
            x₀ ⟨Tuple.entry p i, by
              have hmem : Tuple.entry p i ∈ (kept : Set ℕ) :=
                pairing_entry_mem kept i
              exact (mem_tupleDomain (Sigma.mk m x : Tuple X)).mp hmem.2⟩)
        ≤ coordinateEDistSup x x₀ := by
    apply Finset.sup_le
    intro i _hi
    let j : Fin m := ⟨Tuple.entry p i, by
      have hmem : Tuple.entry p i ∈ (kept : Set ℕ) :=
        pairing_entry_mem kept i
      exact (mem_tupleDomain (Sigma.mk m x : Tuple X)).mp hmem.2⟩
    have hle : edist (x j) (x₀ j) ≤ coordinateEDistSup x x₀ := by
      simpa [coordinateEDistSup] using
        (Finset.le_sup (s := Finset.univ)
          (f := fun k : Fin m => edist (x k) (x₀ k)) (Finset.mem_univ j))
    simpa [j]
      using hle
  calc
    edist (reindex (Sigma.mk m x : Tuple X) eta)
        (reindex (Sigma.mk m x₀ : Tuple X) eta)
        ≤ coordinateEDistSup
          (fun i : Fin p.length =>
            x ⟨Tuple.entry p i, by
              have hmem : Tuple.entry p i ∈ (kept : Set ℕ) :=
                pairing_entry_mem kept i
              exact (mem_tupleDomain (Sigma.mk m x : Tuple X)).mp hmem.2⟩)
          (fun i : Fin p.length =>
            x₀ ⟨Tuple.entry p i, by
              have hmem : Tuple.entry p i ∈ (kept : Set ℕ) :=
                pairing_entry_mem kept i
              exact (mem_tupleDomain (Sigma.mk m x : Tuple X)).mp hmem.2⟩) := by
          simpa [reindex, kept, p, tupleDomain, Tuple.length, Tuple.entry] using
            (fixedLength_edist_le_coordinateEDistSup (X := X)
              (x := fun i : Fin p.length =>
                x ⟨Tuple.entry p i, by
                  have hmem : Tuple.entry p i ∈ (kept : Set ℕ) :=
                    pairing_entry_mem kept i
                  exact (mem_tupleDomain (Sigma.mk m x : Tuple X)).mp hmem.2⟩)
              (y := fun i : Fin p.length =>
                x₀ ⟨Tuple.entry p i, by
                  have hmem : Tuple.entry p i ∈ (kept : Set ℕ) :=
                    pairing_entry_mem kept i
                  exact (mem_tupleDomain (Sigma.mk m x : Tuple X)).mp hmem.2⟩))
    _ ≤ coordinateEDistSup x x₀ := hcoord

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: quantitative estimate inside
`thm:analytic-properties-actions`, cancellation part.

Informal statement: in a fixed-length layer, reindexing along a fixed finite
index set is nonexpansive for the tuple Hausdorff distance, once the input
tuple distance is below the local radius `1`.

Lean strategy / thesis relation note: this is the cancellation proof after the thesis has collapsed
the tuple metric to the coordinate maximum.
-/
theorem reindex_edist_le_of_fixed_lt_one {X : Type u} [EMetricSpace X]
    {m : ℕ} {x x₀ : Fin m → X} (eta : FiniteSubsets ℕ)
    (hx : edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) <
      (1 : ENNReal)) :
    edist (reindex (Sigma.mk m x : Tuple X) eta)
        (reindex (Sigma.mk m x₀ : Tuple X) eta) ≤
      edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) :=
  le_trans (reindex_edist_le_coordinate x x₀ eta)
    (coordinateEDistSup_le_fixedLength_edist_of_lt_one hx)

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: quantitative estimate inside
`thm:analytic-properties-actions`, cancellation part.

Informal statement: in a fixed-length layer, cancellation by a fixed removal
set is nonexpansive, once the input tuple distance is below `1`.

Lean strategy / thesis relation note: the thesis removes a stabilized finite subset of indices. Lean
defines cancellation as reindexing the complement of that removal set inside
the tuple domain.
-/
theorem cancel_edist_le_of_fixed_same_removed_lt_one {X : Type u} [EMetricSpace X]
    {m : ℕ} {x x₀ : Fin m → X} (eta : FiniteSubsets ℕ)
    (hx : edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) <
      (1 : ENNReal)) :
    edist (cancel (Sigma.mk m x : Tuple X) eta)
        (cancel (Sigma.mk m x₀ : Tuple X) eta) ≤
      edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) := by
  simpa [cancel, tupleDomain, Tuple.length] using
    (reindex_edist_le_of_fixed_lt_one
      (eta := finiteSubsetDiff (tupleDomain (Sigma.mk m x : Tuple X)) eta) hx)

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: epsilon-delta estimate inside
`thm:analytic-properties-actions`, cancellation part.

Informal statement: in a fixed-length layer, if the input tuple distance is
below a common bound `δ` and below `1`, then cancellation by a fixed removal
set has output distance below `δ`.
-/
theorem cancel_edist_lt_of_fixed_same_removed {X : Type u} [EMetricSpace X]
    {m : ℕ} {x x₀ : Fin m → X} {δ : ENNReal} (eta : FiniteSubsets ℕ)
    (hx_one : edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) <
      (1 : ENNReal))
    (hxδ : edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) < δ) :
    edist (cancel (Sigma.mk m x : Tuple X) eta)
        (cancel (Sigma.mk m x₀ : Tuple X) eta) < δ :=
  lt_of_le_of_lt (cancel_edist_le_of_fixed_same_removed_lt_one eta hx_one) hxδ

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: `thm:analytic-properties-actions`, cancellation part.

Informal statement: tuple cancellation is continuous for the explicit
topology induced by the tuple and finite-subset Hausdorff extended metrics.

Lean strategy / thesis relation note: this follows the thesis proof directly. Below radius `1`, the
tuple length and the finite set of removed natural-number indices both
stabilize; after that, the fixed-removal estimate applies.
-/
theorem continuousAt_cancel_emetricTopology {X : Type u} [EMetricSpace X]
    (p₀ : Tuple X × FiniteSubsets ℕ) :
    @ContinuousAt (Tuple X × FiniteSubsets ℕ) (Tuple X)
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      (fun p : Tuple X × FiniteSubsets ℕ => cancel p.1 p.2) p₀ := by
  letI : TopologicalSpace (Tuple X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  letI : TopologicalSpace (FiniteSubsets ℕ) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  letI : TopologicalSpace (Tuple X × FiniteSubsets ℕ) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  rcases p₀ with ⟨x₀Tuple, eta₀⟩
  rcases x₀Tuple with ⟨m, x₀⟩
  rw [ContinuousAt, EMetric.tendsto_nhds_nhds]
  intro ε hε
  let δ : ENNReal := min ε (1 : ENNReal)
  refine ⟨δ, lt_min hε zero_lt_one, ?_⟩
  intro p hp
  rcases p with ⟨xTuple, eta⟩
  rcases xTuple with ⟨m', x⟩
  rw [Prod.edist_eq] at hp
  have hxδ :
      edist (Sigma.mk m' x : Tuple X) (Sigma.mk m x₀ : Tuple X) < δ :=
    (max_lt_iff.mp hp).1
  have hetaδ : edist eta eta₀ < δ :=
    (max_lt_iff.mp hp).2
  have hx_one :
      edist (Sigma.mk m' x : Tuple X) (Sigma.mk m x₀ : Tuple X) <
        (1 : ENNReal) :=
    lt_of_lt_of_le hxδ (min_le_right _ _)
  have heta_one : edist eta eta₀ < (1 : ENNReal) :=
    lt_of_lt_of_le hetaδ (min_le_right _ _)
  have hm : m' = m := by
    simpa [Tuple.length] using length_eq_of_edist_lt_one hx_one
  have heta : eta = eta₀ := finiteSubsets_nat_eq_of_edist_lt_one heta_one
  subst m'
  subst eta
  have houtδ :
      edist (cancel (Sigma.mk m x : Tuple X) eta₀)
          (cancel (Sigma.mk m x₀ : Tuple X) eta₀) < δ :=
    cancel_edist_lt_of_fixed_same_removed eta₀ hx_one hxδ
  exact lt_of_lt_of_le houtδ (min_le_left _ _)

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: `thm:analytic-properties-actions`, cancellation part.

Informal statement: tuple cancellation is continuous for the explicit
extended-metric topology.
-/
theorem continuous_cancel_emetricTopology {X : Type u} [EMetricSpace X] :
    @Continuous (Tuple X × FiniteSubsets ℕ) (Tuple X)
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      (fun p : Tuple X × FiniteSubsets ℕ => cancel p.1 p.2) := by
  letI : TopologicalSpace (Tuple X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  letI : TopologicalSpace (FiniteSubsets ℕ) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  letI : TopologicalSpace (Tuple X × FiniteSubsets ℕ) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  rw [continuous_iff_continuousAt]
  exact continuousAt_cancel_emetricTopology

/-! ## Modification -/

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: index-stabilization step inside
`thm:analytic-properties-actions`, modification part.

Informal statement: if two distinct finite modification sets are within
Hausdorff distance `< 1`, then they modify exactly the same natural-number
indices.

Lean strategy / thesis relation note: this is a direct reuse of the earlier
`lem:helpful-distinct` formalization for distinct finite sets.

Lean strategy / thesis strategy note: the full thesis lemma is already formalized in
`FiniteSets.lean` as the same-index nearby-point theorem and equal-cardinality
theorem. This declaration records only the index-set consequence needed for
modification continuity.
-/
theorem modification_indexSet_eq_of_near {X : Type u} [EMetricSpace X]
    {xi xi₀ : DistinctFiniteSubsets X}
    (hxi : edist xi xi₀ < (1 : ENNReal)) :
    DistinctFiniteSubsets.indexSet xi =
      DistinctFiniteSubsets.indexSet xi₀ :=
  DistinctFiniteSubsets.indexSet_eq_of_edist_lt_one hxi

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: non-modified-coordinate step inside
`thm:analytic-properties-actions`, modification part.

Informal statement: after the modification index set stabilizes, absence of a
replacement at an index is preserved.
-/
theorem modification_no_value_of_indexSet_eq {X : Type u}
    {xi xi₀ : DistinctFiniteSubsets X}
    (hidx : DistinctFiniteSubsets.indexSet xi =
      DistinctFiniteSubsets.indexSet xi₀)
    {n : ℕ}
    (hnone : ¬ ∃ z : X,
      IndexAugmented.mk n z ∈ (xi.1 : Set (IndexAugmented X))) :
    ¬ ∃ z : X,
      IndexAugmented.mk n z ∈ (xi₀.1 : Set (IndexAugmented X)) := by
  intro hsome
  have hn₀ : n ∈ (DistinctFiniteSubsets.indexSet xi₀ : Set ℕ) :=
    (DistinctFiniteSubsets.mem_indexSet xi₀).mpr hsome
  have hn : n ∈ (DistinctFiniteSubsets.indexSet xi : Set ℕ) := by
    simpa [hidx] using hn₀
  exact hnone ((DistinctFiniteSubsets.mem_indexSet xi).mp hn)

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: non-modified-coordinate step inside
`thm:analytic-properties-actions`, modification part.

Informal statement: below radius `1`, if the first modification set has no
replacement at an index, neither does the second.
-/
theorem modification_no_value_of_near {X : Type u} [EMetricSpace X]
    {xi xi₀ : DistinctFiniteSubsets X}
    (hxi : edist xi xi₀ < (1 : ENNReal)) {n : ℕ}
    (hnone : ¬ ∃ z : X,
      IndexAugmented.mk n z ∈ (xi.1 : Set (IndexAugmented X))) :
    ¬ ∃ z : X,
      IndexAugmented.mk n z ∈ (xi₀.1 : Set (IndexAugmented X)) :=
  modification_no_value_of_indexSet_eq (modification_indexSet_eq_of_near hxi) hnone

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: modified-coordinate step inside
`thm:analytic-properties-actions`, modification part.

Informal statement: if a replacement value occurs at an index in the first
modification set, then a nearby replacement value occurs at the same index in
the second modification set.

Lean strategy / thesis relation note: the theorem uses the thesis' radius restriction `r ≤ 1`, which
is what forces the matching point in the Hausdorff comparison to have the same
natural-number index.
-/
theorem modificationValue_edist_lt_of_mem {X : Type u} [EMetricSpace X]
    {xi xi₀ : DistinctFiniteSubsets X} {r : ENNReal}
    (hr : r ≤ (1 : ENNReal)) (hxi : edist xi xi₀ < r)
    {n : ℕ} {z default default₀ : X}
    (hz : IndexAugmented.mk n z ∈ (xi.1 : Set (IndexAugmented X))) :
    edist (modificationValue xi n default)
        (modificationValue xi₀ n default₀) < r := by
  rcases DistinctFiniteSubsets.exists_same_index_near_of_edist_lt hr hxi hz with
    ⟨w, hzw, hw⟩
  have hleft : modificationValue xi n default = z :=
    modificationValue_eq_of_mem xi hz
  have hright : modificationValue xi₀ n default₀ = w :=
    modificationValue_eq_of_mem xi₀ hw
  simpa [hleft, hright] using hzw

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: coordinate estimate inside
`thm:analytic-properties-actions`, modification part.

Informal statement: in a fixed-length layer, each modified output coordinate
is within `δ` if both the original tuple and the modification set are within
`δ`, with `δ ≤ 1`.

Lean strategy / thesis relation note: this is the thesis proof split into two cases: modified
coordinates use the distinct-finite-set Hausdorff estimate; unmodified
coordinates use the tuple coordinate estimate.
-/
theorem modify_entry_edist_lt_of_fixed_near {X : Type u} [EMetricSpace X]
    {m : ℕ} {x x₀ : Fin m → X}
    {xi xi₀ : DistinctFiniteSubsets X} {δ : ENNReal}
    (hδle : δ ≤ (1 : ENNReal))
    (hxδ : edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) < δ)
    (hxiδ : edist xi xi₀ < δ) (i : Fin m) :
    edist (Tuple.entry (Primitive.modify (Sigma.mk m x : Tuple X) xi) i)
        (Tuple.entry (Primitive.modify (Sigma.mk m x₀ : Tuple X) xi₀) i) < δ := by
  have hx_one : edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) <
      (1 : ENNReal) :=
    lt_of_lt_of_le hxδ hδle
  have hxi_one : edist xi xi₀ < (1 : ENNReal) :=
    lt_of_lt_of_le hxiδ hδle
  by_cases hmem : ∃ z : X,
      IndexAugmented.mk i.1 z ∈ (xi.1 : Set (IndexAugmented X))
  · rcases hmem with ⟨z, hz⟩
    simpa [Primitive.modify, Tuple.entry] using
      (modificationValue_edist_lt_of_mem hδle hxiδ
        (default := x i) (default₀ := x₀ i) hz)
  · have hmem₀ : ¬ ∃ z : X,
        IndexAugmented.mk i.1 z ∈ (xi₀.1 : Set (IndexAugmented X)) :=
      modification_no_value_of_near hxi_one hmem
    have hleft : modificationValue xi i.1 (x i) = x i :=
      modificationValue_eq_default_of_not_exists xi hmem
    have hright : modificationValue xi₀ i.1 (x₀ i) = x₀ i :=
      modificationValue_eq_default_of_not_exists xi₀ hmem₀
    have hcoord_le :
        edist (x i) (x₀ i) ≤
          edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) :=
      coordinate_edist_le_fixedLength_edist_of_lt_one hx_one i
    have hcoord_lt : edist (x i) (x₀ i) < δ :=
      lt_of_le_of_lt hcoord_le hxδ
    simpa [Primitive.modify, Tuple.entry, hleft, hright] using hcoord_lt

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: epsilon-delta estimate inside
`thm:analytic-properties-actions`, modification part.

Informal statement: in a fixed-length layer, if the original tuple and
distinct finite modification set are both within `δ`, with `δ ≤ 1`, then the
modified output tuples are within `δ`.

Lean strategy / thesis relation note: the proof follows the thesis: length is unchanged by
modification, the fixed-length tuple metric collapses to coordinate control,
and each coordinate is handled by the modified/unmodified case split above.
-/
theorem modify_edist_lt_of_fixed_near {X : Type u} [EMetricSpace X]
    {m : ℕ} {x x₀ : Fin m → X}
    {xi xi₀ : DistinctFiniteSubsets X} {δ : ENNReal}
    (hδle : δ ≤ (1 : ENNReal))
    (hxδ : edist (Sigma.mk m x : Tuple X) (Sigma.mk m x₀ : Tuple X) < δ)
    (hxiδ : edist xi xi₀ < δ) :
    edist (Primitive.modify (Sigma.mk m x : Tuple X) xi)
        (Primitive.modify (Sigma.mk m x₀ : Tuple X) xi₀) < δ := by
  have hδpos : (⊥ : ENNReal) < δ := lt_of_le_of_lt bot_le hxδ
  have hcoord :
      coordinateEDistSup
          (fun i : Fin m =>
            Tuple.entry (Primitive.modify (Sigma.mk m x : Tuple X) xi) i)
          (fun i : Fin m =>
            Tuple.entry (Primitive.modify (Sigma.mk m x₀ : Tuple X) xi₀) i) < δ := by
    rw [coordinateEDistSup]
    exact (Finset.sup_lt_iff hδpos).mpr
      (fun i _hi => modify_entry_edist_lt_of_fixed_near hδle hxδ hxiδ i)
  calc
    edist (Primitive.modify (Sigma.mk m x : Tuple X) xi)
        (Primitive.modify (Sigma.mk m x₀ : Tuple X) xi₀)
        ≤ coordinateEDistSup
          (fun i : Fin m =>
            Tuple.entry (Primitive.modify (Sigma.mk m x : Tuple X) xi) i)
          (fun i : Fin m =>
            Tuple.entry (Primitive.modify (Sigma.mk m x₀ : Tuple X) xi₀) i) := by
          simpa [Primitive.modify, Tuple.length, Tuple.entry] using
            (fixedLength_edist_le_coordinateEDistSup (X := X)
              (x := fun i : Fin m =>
                Tuple.entry (Primitive.modify (Sigma.mk m x : Tuple X) xi) i)
              (y := fun i : Fin m =>
                Tuple.entry (Primitive.modify (Sigma.mk m x₀ : Tuple X) xi₀) i))
    _ < δ := hcoord

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: `thm:analytic-properties-actions`, modification part.

Informal statement: tuple modification is continuous for the explicit
topology induced by the tuple and distinct-finite-set Hausdorff extended
metrics.

Lean strategy / thesis relation note: as in the thesis proof, the tuple length stabilizes below
radius `1`; distinct finite modification sets then have the same modified
indices, and each coordinate is controlled by the fixed-layer estimate above.
-/
theorem continuousAt_modify_emetricTopology {X : Type u} [EMetricSpace X]
    (p₀ : Tuple X × DistinctFiniteSubsets X) :
    @ContinuousAt (Tuple X × DistinctFiniteSubsets X) (Tuple X)
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      (fun p : Tuple X × DistinctFiniteSubsets X => Primitive.modify p.1 p.2) p₀ := by
  letI : TopologicalSpace (Tuple X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  letI : TopologicalSpace (DistinctFiniteSubsets X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  letI : TopologicalSpace (Tuple X × DistinctFiniteSubsets X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  rcases p₀ with ⟨x₀Tuple, xi₀⟩
  rcases x₀Tuple with ⟨m, x₀⟩
  rw [ContinuousAt, EMetric.tendsto_nhds_nhds]
  intro ε hε
  let δ : ENNReal := min ε (1 : ENNReal)
  refine ⟨δ, lt_min hε zero_lt_one, ?_⟩
  intro p hp
  rcases p with ⟨xTuple, xi⟩
  rcases xTuple with ⟨m', x⟩
  rw [Prod.edist_eq] at hp
  have hxδ :
      edist (Sigma.mk m' x : Tuple X) (Sigma.mk m x₀ : Tuple X) < δ :=
    (max_lt_iff.mp hp).1
  have hxiδ : edist xi xi₀ < δ :=
    (max_lt_iff.mp hp).2
  have hx_one :
      edist (Sigma.mk m' x : Tuple X) (Sigma.mk m x₀ : Tuple X) <
        (1 : ENNReal) :=
    lt_of_lt_of_le hxδ (min_le_right _ _)
  have hm : m' = m := by
    simpa [Tuple.length] using length_eq_of_edist_lt_one hx_one
  subst m'
  have houtδ :
      edist (Primitive.modify (Sigma.mk m x : Tuple X) xi)
          (Primitive.modify (Sigma.mk m x₀ : Tuple X) xi₀) < δ :=
    modify_edist_lt_of_fixed_near (min_le_right _ _) hxδ hxiδ
  exact lt_of_lt_of_le houtδ (min_le_left _ _)

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: `thm:analytic-properties-actions`, modification part.

Informal statement: tuple modification is continuous for the explicit
extended-metric topology.
-/
theorem continuous_modify_emetricTopology {X : Type u} [EMetricSpace X] :
    @Continuous (Tuple X × DistinctFiniteSubsets X) (Tuple X)
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
      (fun p : Tuple X × DistinctFiniteSubsets X => Primitive.modify p.1 p.2) := by
  letI : TopologicalSpace (Tuple X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  letI : TopologicalSpace (DistinctFiniteSubsets X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  letI : TopologicalSpace (Tuple X × DistinctFiniteSubsets X) :=
    PseudoEMetricSpace.toUniformSpace.toTopologicalSpace
  rw [continuous_iff_continuousAt]
  exact continuousAt_modify_emetricTopology

/-! ## Measurability of Sorted Primitive Operations -/

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: hypothesis used by `cor:sorted-operations-measurable`.

Informal statement: a sorting rule is measurable when its map from tuple space
to sorted tuple space is Borel measurable for the thesis extended-metric
topologies.

Lean strategy / thesis relation note: the thesis' later `thm:measurable-sorting-exists` supplies
such sorting rules; in this project that theorem is proved in
`TuplesMeasurableSorting.lean` as
`exists_measurableSortingRule_of_borelOrder`. The market-action corollary is
formalized here in the conditional form used by the proof, so this predicate
is a hypothesis interface rather than the theorem-level existence result.
-/
noncomputable def IsMeasurableSortingRule {X : Type u}
    [EMetricSpace X] [Preorder X] (varsigma : SortingRule X) : Prop :=
  @Measurable (Tuple X) (SortedTuple X)
    (emetricBorel (Tuple X)) (emetricBorel (SortedTuple X))
    varsigma.toSortedTuple

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: primitive-operation input for
`cor:sorted-operations-measurable`.

Informal statement: ordinary tuple concatenation is Borel measurable for the
thesis extended-metric Borel structures.
-/
theorem measurable_concat_emetricBorel {X : Type u} [EMetricSpace X] :
    @Measurable (Tuple X × Tuple X) (Tuple X)
      (emetricBorel (Tuple X × Tuple X)) (emetricBorel (Tuple X))
      (fun p : Tuple X × Tuple X => concat p.1 p.2) := by
  letI : TopologicalSpace (Tuple X) := emetricTopology (Tuple X)
  letI : MeasurableSpace (Tuple X) := emetricBorel (Tuple X)
  letI : OpensMeasurableSpace (Tuple X) := ⟨le_rfl⟩
  letI : BorelSpace (Tuple X) := ⟨rfl⟩
  letI : TopologicalSpace (Tuple X × Tuple X) :=
    emetricTopology (Tuple X × Tuple X)
  letI : MeasurableSpace (Tuple X × Tuple X) :=
    emetricBorel (Tuple X × Tuple X)
  letI : OpensMeasurableSpace (Tuple X × Tuple X) := ⟨le_rfl⟩
  exact continuous_concat_emetricTopology.measurable

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: primitive-operation input for
`cor:sorted-operations-measurable`.

Informal statement: ordinary tuple cancellation is Borel measurable for the
thesis extended-metric Borel structures.
-/
theorem measurable_cancel_emetricBorel {X : Type u} [EMetricSpace X] :
    @Measurable (Tuple X × FiniteSubsets ℕ) (Tuple X)
      (emetricBorel (Tuple X × FiniteSubsets ℕ)) (emetricBorel (Tuple X))
      (fun p : Tuple X × FiniteSubsets ℕ => cancel p.1 p.2) := by
  letI : TopologicalSpace (Tuple X) := emetricTopology (Tuple X)
  letI : MeasurableSpace (Tuple X) := emetricBorel (Tuple X)
  letI : OpensMeasurableSpace (Tuple X) := ⟨le_rfl⟩
  letI : BorelSpace (Tuple X) := ⟨rfl⟩
  letI : TopologicalSpace (FiniteSubsets ℕ) :=
    emetricTopology (FiniteSubsets ℕ)
  letI : MeasurableSpace (FiniteSubsets ℕ) :=
    emetricBorel (FiniteSubsets ℕ)
  letI : TopologicalSpace (Tuple X × FiniteSubsets ℕ) :=
    emetricTopology (Tuple X × FiniteSubsets ℕ)
  letI : MeasurableSpace (Tuple X × FiniteSubsets ℕ) :=
    emetricBorel (Tuple X × FiniteSubsets ℕ)
  letI : OpensMeasurableSpace (Tuple X × FiniteSubsets ℕ) := ⟨le_rfl⟩
  exact continuous_cancel_emetricTopology.measurable

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: primitive-operation input for
`cor:sorted-operations-measurable`.

Informal statement: ordinary tuple modification is Borel measurable for the
thesis extended-metric Borel structures.
-/
theorem measurable_modify_emetricBorel {X : Type u} [EMetricSpace X] :
    @Measurable (Tuple X × DistinctFiniteSubsets X) (Tuple X)
      (emetricBorel (Tuple X × DistinctFiniteSubsets X))
      (emetricBorel (Tuple X))
      (fun p : Tuple X × DistinctFiniteSubsets X => Primitive.modify p.1 p.2) := by
  letI : TopologicalSpace (Tuple X) := emetricTopology (Tuple X)
  letI : MeasurableSpace (Tuple X) := emetricBorel (Tuple X)
  letI : OpensMeasurableSpace (Tuple X) := ⟨le_rfl⟩
  letI : BorelSpace (Tuple X) := ⟨rfl⟩
  letI : TopologicalSpace (DistinctFiniteSubsets X) :=
    emetricTopology (DistinctFiniteSubsets X)
  letI : MeasurableSpace (DistinctFiniteSubsets X) :=
    emetricBorel (DistinctFiniteSubsets X)
  letI : TopologicalSpace (Tuple X × DistinctFiniteSubsets X) :=
    emetricTopology (Tuple X × DistinctFiniteSubsets X)
  letI : MeasurableSpace (Tuple X × DistinctFiniteSubsets X) :=
    emetricBorel (Tuple X × DistinctFiniteSubsets X)
  letI : OpensMeasurableSpace (Tuple X × DistinctFiniteSubsets X) := ⟨le_rfl⟩
  exact continuous_modify_emetricTopology.measurable

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: `cor:sorted-operations-measurable`, sorted addition part.

Informal statement: if the chosen sorting rule is measurable, then sorted
tuple addition is measurable.

Lean strategy / thesis relation note: this is composition of measurable concatenation with the
measurable sorting rule, matching the thesis proof.
-/
theorem measurable_sortedAdd_emetricBorel {X : Type u}
    [EMetricSpace X] [Preorder X] (varsigma : SortingRule X)
    (hvarsigma : IsMeasurableSortingRule varsigma) :
    @Measurable (Tuple X × Tuple X) (SortedTuple X)
      (emetricBorel (Tuple X × Tuple X)) (emetricBorel (SortedTuple X))
      (fun p : Tuple X × Tuple X => sortedAdd varsigma p.1 p.2) := by
  change @Measurable (Tuple X × Tuple X) (SortedTuple X)
    (emetricBorel (Tuple X × Tuple X)) (emetricBorel (SortedTuple X))
    (fun p : Tuple X × Tuple X => varsigma.toSortedTuple (concat p.1 p.2))
  exact hvarsigma.comp measurable_concat_emetricBorel

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: `cor:sorted-operations-measurable`, sorted cancellation part.

Informal statement: if the chosen sorting rule is measurable, then sorted
cancellation is measurable.
-/
theorem measurable_sortedCancel_emetricBorel {X : Type u}
    [EMetricSpace X] [Preorder X] (varsigma : SortingRule X)
    (hvarsigma : IsMeasurableSortingRule varsigma) :
    @Measurable (Tuple X × FiniteSubsets ℕ) (SortedTuple X)
      (emetricBorel (Tuple X × FiniteSubsets ℕ)) (emetricBorel (SortedTuple X))
      (fun p : Tuple X × FiniteSubsets ℕ => sortedCancel varsigma p.1 p.2) := by
  change @Measurable (Tuple X × FiniteSubsets ℕ) (SortedTuple X)
    (emetricBorel (Tuple X × FiniteSubsets ℕ)) (emetricBorel (SortedTuple X))
    (fun p : Tuple X × FiniteSubsets ℕ => varsigma.toSortedTuple (cancel p.1 p.2))
  exact hvarsigma.comp measurable_cancel_emetricBorel

/--
Thesis source:
`1 - theoretical foundations/3_market_actions.tex`, subsection
"Analytical Results for Primitive Actions".

Original label: `cor:sorted-operations-measurable`, sorted modification part.

Informal statement: if the chosen sorting rule is measurable, then sorted
modification is measurable.
-/
theorem measurable_sortedModify_emetricBorel {X : Type u}
    [EMetricSpace X] [Preorder X] (varsigma : SortingRule X)
    (hvarsigma : IsMeasurableSortingRule varsigma) :
    @Measurable (Tuple X × DistinctFiniteSubsets X) (SortedTuple X)
      (emetricBorel (Tuple X × DistinctFiniteSubsets X))
      (emetricBorel (SortedTuple X))
      (fun p : Tuple X × DistinctFiniteSubsets X =>
        sortedModify varsigma p.1 p.2) := by
  change @Measurable (Tuple X × DistinctFiniteSubsets X) (SortedTuple X)
    (emetricBorel (Tuple X × DistinctFiniteSubsets X)) (emetricBorel (SortedTuple X))
    (fun p : Tuple X × DistinctFiniteSubsets X =>
      varsigma.toSortedTuple (Primitive.modify p.1 p.2))
  exact hvarsigma.comp measurable_modify_emetricBorel

end Analytic
end MarketActions
end Foundations
end Thesis
